// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApi3UOiLn1EjhOthH37TS_ZOrSd3VMthA',
    appId: '1:505060126624:web:ae9e5fb7c02997090cfec5',
    messagingSenderId: '505060126624',
    projectId: 'chat-firebase-flutter-f351c',
    authDomain: 'chat-firebase-flutter-f351c.firebaseapp.com',
    storageBucket: 'chat-firebase-flutter-f351c.appspot.com',
    measurementId: 'G-10JS5X301H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-5vWKnxgrNl0XH43EFVOKALaYhQ6iY0',
    appId: '1:505060126624:android:885067554d067e8f0cfec5',
    messagingSenderId: '505060126624',
    projectId: 'chat-firebase-flutter-f351c',
    storageBucket: 'chat-firebase-flutter-f351c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChCzyc6QQGKIzIM9dbLqJFE5j_empmY-w',
    appId: '1:505060126624:ios:42cffff861a34c1a0cfec5',
    messagingSenderId: '505060126624',
    projectId: 'chat-firebase-flutter-f351c',
    storageBucket: 'chat-firebase-flutter-f351c.appspot.com',
    iosClientId: '505060126624-2mu4rgilcbi1q2hi9d3st85vvpk7j13r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChCzyc6QQGKIzIM9dbLqJFE5j_empmY-w',
    appId: '1:505060126624:ios:42cffff861a34c1a0cfec5',
    messagingSenderId: '505060126624',
    projectId: 'chat-firebase-flutter-f351c',
    storageBucket: 'chat-firebase-flutter-f351c.appspot.com',
    iosClientId: '505060126624-2mu4rgilcbi1q2hi9d3st85vvpk7j13r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutterFirebase',
  );
}
